### PR TITLE
Milestone-2 : Mint.com's signup page

### PR DESCRIPTION
**Pull request by hemantso**
## Project-2:- mint.com's sign up page
-Navbar having a sign-in button and forgot password link, Intuit logo with link used with background image
- form page with email, phone, and password as input field
- a footer with privacy condition

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review by Tolulope Olusakin
Please check on this in a few minutes for some feedback!

**Comment by nikasulo** [comment]
# Great work building this team! @hemant-soni-vst-au4 and @arslanbisharat 
I have looked over your project thoroughly and it's really great! There are a few things I would like to suggest you look into, please see them below:

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review.

#### Live link
Please remember to update the live link in your project to point to the actual website. My go to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires some changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
Here are the things you need to change before this project can be approved:
* [x] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
* [x] Live link is still not working like @Oluwadamilareolusakin pointed in his review.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi Team, you have done a great job fixing all the comments requested by the previous reviewers 👍 
Your live version is now working properly and you have passed the stickler checks as well 😄 On this note I, therefore, approved your project. Go ahead and merge to master and submit project completion form.

Good luck with your next projects 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Pull request merged**
